Update code to support Sysl union type.
anz-bank/sysl-go pull request #198
Opened 2020-08-14 04:19 UTC by ericzhang6222

2020-08-14 04:41 UTC, orlade-anz requested changes
Generally LGTM I think, but I'm not super familiar with sysl-go yet. I'd like an approval from someone who is.

2020-08-14 04:41 UTC, orlade-anz commented on codegen/arrai/svc_types.arrai
> +            ${value('oneOf')('type').a >> .('typeRef')('ref')('path').a >> ('// ' + .@item.s)::\i}
Nit: style
```suggestion
            ${value('oneOf')('type').a >> .('typeRef')('ref')('path').a >> $`// ${.@item.s}`::\i}
```

2020-08-14 05:09 UTC, andrewemeryanz requested changes
Overall approach good. Minor change requested to make the relationship between union types explicit.

2020-08-14 05:09 UTC, andrewemeryanz commented on codegen/tests/simple/types.go
> +type Cat struct {
We should go a little further and make the relationship explicit:

```go
func (c Cat) isPet() {}
func (d Dog) isPet() {}
type Pet interface {
	isPet()
}
```

2020-08-14 05:10 UTC, springwiz submitted a review, later dismissed

2020-08-14 05:15 UTC, springwiz requested changes
I see an issue lurking over here, as per my understanding, both Cat and Dog can behave as Pet during runtime as they are part of a union(both implement Pet interface {}). But essentially in the generated code the method set associated with  Pet interface {} is empty, which means even a struct like type struct Empty {} can be a Pet. Please add a method to the Pet interface {} and implement the same in the structs Cat and Dog.

2020-08-14 06:07 UTC, ericzhang6222 commented
> I see an issue lurking over here, as per my understanding, both Cat and Dog can behave as Pet during runtime as they are part of a union(both implement Pet interface {}). But essentially in the generated code the method set associated with Pet interface {} is empty, which means even a struct like type struct Empty {} can be a Pet. Please add a method to the Pet interface {} and implement the same in the structs Cat and Dog.

Fixed.

2020-08-14 07:25 UTC, springwiz approved these changes
LGTM

2020-08-16 22:51 UTC, andrewemeryanz requested changes

2020-08-16 22:51 UTC, andrewemeryanz commented on codegen/tests/simple/types.go
> +	IsPetA() bool
Method should be `isPetA()`:
1. We don't want to export the method we just want to mark the implementations.
1. We don't need to return anything; void will suffice.

2020-08-17 02:18 UTC, andrewemeryanz approved these changes

2020-08-17 02:34 UTC, orlade-anz approved these changes

2020-08-17 03:06 UTC, merged