Fixed some minor grpc arrai transform typos
anz-bank/sysl-go pull request #208
Opened 2020-08-26 04:42 UTC by nydrani

Added sysl call and return parameter detection

2020-08-26 05:48 UTC, anzdaddy reviewed
Still reviewing. These three comments are just a suggestion.

2020-08-26 05:48 UTC, anzdaddy commented on codegen/arrai/grpc_handler.arrai
> +            let sig = methodSig(ep);
```suggestion
            methodSig(ep) -> $`
```
… and remove the next line.

2020-08-26 05:48 UTC, anzdaddy commented on codegen/arrai/grpc_handler.arrai
> +                        return s.unimpl.${sig.name}(ctx, ${sig.pname})
```suggestion
                // ${.name} ...
                func (s *GrpcServiceHandler) ${.name}(ctx context.Context, ${.pname} *pb.${.ptype}) (*pb.${.rparam}, error) {
                    if s.serviceInterface.${.name} == nil {
                        return s.unimpl.${.name}(ctx, ${.pname})
```

2020-08-26 05:48 UTC, anzdaddy commented on codegen/arrai/grpc_handler.arrai
> +                    return s.serviceInterface.${sig.name}(ctx, ${sig.pname}, client)
```suggestion
                    return s.serviceInterface.${.name}(ctx, ${.pname}, client)
```

2020-08-26 06:01 UTC, nydrani commented on codegen/arrai/grpc_handler.arrai
> +            let sig = methodSig(ep);
Ack

2020-08-26 06:01 UTC, nydrani commented on codegen/arrai/grpc_handler.arrai
> +                        return s.unimpl.${sig.name}(ctx, ${sig.pname})
Ack

2020-08-26 06:01 UTC, nydrani commented on codegen/arrai/grpc_handler.arrai
> +                    return s.serviceInterface.${sig.name}(ctx, ${sig.pname}, client)
Ack

2020-08-26 06:44 UTC, anzdaddy requested changes
Sorry for being so prescriptive. It was the easiest way to clarify in my own head what I wanted.

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_interface.arrai
> +        );
Refactor into grpc.arrai (new file).

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_interface.arrai
> +                $`${sig.name} func(ctx context.Context, ${sig.pname} *pb.${sig.ptype}, client ${sig.name}Client) (*pb.${sig.rparam}, error)`
```suggestion
                (methodSig(ep) -> $`${.name} func${.paramsWithClient})`
```

2020-08-26 06:44 UTC, anzdaddy commented on codegen/testdata/advancedgrpc/README.md
> +A advanced gRPC server specification in SySL and Protobuf format. Usually the `.proto` would be generated from the `.sysl` but at the time of writing that transformation was not available.
```suggestion
An advanced gRPC server specification in Sysl and Protobuf format. Usually the `.proto` would be generated from the `.sysl` but at the time of writing that transformation was not available.
```

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_handler.arrai
> +        );
Refactor into grpc.arrai (new file).

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_client.arrai
> +        );
Refactor into grpc.arrai (new file).

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_client.arrai
> +                $`${sig.name}(ctx context.Context, ${sig.pname} *pb.${sig.ptype}) (*pb.${sig.rparam}, error)`
```suggestion
                methodSig(ep) -> $`${.name}${.params}`
```

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_client.arrai
> +            let sig = methodSig(ep);
```suggestion
            methodSig(ep) -> $`
```
…and remove the next line.

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_client.arrai
> +                    return s.client.${sig.name}(ctx, ${sig.pname})
```suggestion
                // ${.name} ...
                func (s *Client) ${.name}${.params} {
                    return s.client.${.name}(ctx, ${.pname})
```

2020-08-26 06:44 UTC, anzdaddy commented on codegen/arrai/grpc_client.arrai
> +        );
```suggestion
        let ptype = go.type(ptype);
        let params = \withClient $`
            (ctx context.Context, ${.pname} *pb.${.ptype}${withClient && $`, client ${.name}Client`}) (*pb.${.rparam}, error)
        `;
        (
            :name,
            :pname,
            :ptype,
            :rparam,
            params: params(false),
            paramsWithClient: params(true),
        );
```

2020-08-26 06:46 UTC, anzdaddy commented on codegen/arrai/grpc_interface.arrai
> +                $`${sig.name} func(ctx context.Context, ${sig.pname} *pb.${sig.ptype}, client ${sig.name}Client) (*pb.${sig.rparam}, error)`
⚠️ Hmm. This can be a one-liner now.

2020-08-27 02:27 UTC, nydrani commented on codegen/arrai/grpc_interface.arrai
> +        );
Ack

2020-08-27 02:27 UTC, nydrani commented on codegen/arrai/grpc_interface.arrai
> +                $`${sig.name} func(ctx context.Context, ${sig.pname} *pb.${sig.ptype}, client ${sig.name}Client) (*pb.${sig.rparam}, error)`
Ack

2020-08-27 02:27 UTC, nydrani commented on codegen/arrai/grpc_handler.arrai
> +        );
Ack

2020-08-27 02:27 UTC, nydrani commented on codegen/arrai/grpc_client.arrai
> +        );
Ack

2020-08-27 02:28 UTC, nydrani commented on codegen/arrai/grpc_client.arrai
> +                $`${sig.name}(ctx context.Context, ${sig.pname} *pb.${sig.ptype}) (*pb.${sig.rparam}, error)`
Ack

2020-08-27 02:28 UTC, nydrani commented on codegen/arrai/grpc_client.arrai
> +            let sig = methodSig(ep);
Ack

2020-08-27 02:28 UTC, nydrani commented on codegen/arrai/grpc_client.arrai
> +                    return s.client.${sig.name}(ctx, ${sig.pname})
Ack

2020-08-27 02:28 UTC, nydrani commented on codegen/arrai/grpc_client.arrai
> +        );
Ack

2020-08-27 02:29 UTC, nydrani commented on codegen/testdata/advancedgrpc/README.md
> +A advanced gRPC server specification in SySL and Protobuf format. Usually the `.proto` would be generated from the `.sysl` but at the time of writing that transformation was not available.
This ended up just being a copy paste from simplegrpc

2020-08-27 06:55 UTC, anzdaddy approved these changes
One small nit.

2020-08-27 06:55 UTC, anzdaddy commented on codegen/arrai/grpc_client.arrai
> +                $`${sig.name}${sig.params}`
nit:
```suggestion
                grpc.methodSig(ep) -> $`${.name}${.params}`
```

2020-08-27 06:56 UTC, merged