Chloe/load config
anz-bank/sysl-go pull request #37
Opened 2020-03-20 09:04 UTC by ChloePlanet

Fixed #3.

Changes proposed in this pull request:
- [x] func ReadConfig: reads from a single config file and populates both custom, library and genCode config structs
- [ ] auto-generate downstream config struct and populate it

2020-03-23 22:57 UTC, andrewemeryanz commented on config/config.go
> +		viper.SetConfigFile(cfgFile)
Can we do this without `viper` by parsing the yaml contents directly. `viper` is an unnecessary dependency if it can be done without it simply.

2020-03-25 22:57 UTC, andrewemeryanz requested changes
Approach and testing look good. Couple of necessary changes though.

2020-03-25 22:57 UTC, andrewemeryanz commented on config/config_test.go
> +	"github.com/alecthomas/assert"
Please replace with `github.com/alecthomas/assert` with `github.com/stretchr/testify/require` to keep consistent with other tests.

2020-03-25 22:57 UTC, andrewemeryanz commented on config/testdata/config.yaml
> +    fenergo:
This really needs to be made anonymous, meaning `fenergo` should be renamed to `foo` or similar and urls need to changed.

2020-03-25 22:57 UTC, andrewemeryanz commented on config/testdata/config.yaml
> +    getV1BffFenergoAPIDocs:
Remove any unnecessary config: `getV1StatementOfPositionCustomer` isn't used outside this file.

2020-03-26 19:53 UTC, anzdaddy approved these changes

2020-03-27 03:27 UTC, andrewemeryanz approved these changes
Looks good.

2020-03-27 03:27 UTC, andrewemeryanz commented on Makefile
> +	go test -count=1 -cover -coverprofile=$(COVERFILE) -tags codeanalysis ./...
This change could probably be a separate pull request.

2020-03-27 03:48 UTC, merged