make build metadata opinionated
anz-bank/sysl-go pull request #50
Opened 2020-03-27 04:32 UTC by tiagralee

issue #4 

- Add build metadata to the core and set default value in build time
- Removed the previous buildmetadata param in server initialise

2020-03-27 05:12 UTC, andrewemeryanz requested changes
One minor change, otherwise fine.

2020-03-27 05:12 UTC, andrewemeryanz commented on core/server.go
> -func Server(ctx context.Context, name string, hl Manager, grpcHl GrpcManager, logger *logrus.Logger, promRegistry *prometheus.Registry, buildMetadata *status.BuildMetadata) error {
This parameter can also be removed from `core.configureAdminServerListener`.

2020-03-27 05:19 UTC, cuminandpaprika commented on core/build_metadata.go
> +	//  go build -ldflags="-X main.Name=BFF -X main.Version=1.0" ...etc...
Could we replace this example with something more generic?
e.g BFF isn't very clear as an application name. Something like `TestApp` or `DemoApp` could be more appropriate?

2020-03-29 20:54 UTC, andrewemeryanz commented
Looks good. Can you squash these changes into a single commit:
```sh
git reset --soft HEAD~3
git commit
```

and put a more descriptive commit message, something like:

```
Add build metadata

This change adds the ability to set build metadata at build time. Build
metadata is regarded as data that is common to all server builds (name, 
version, etc.).
```

2020-03-29 22:19 UTC, cuminandpaprika reviewed
Looks good! 

One more thing that would be super helpful for any users is to document the need to run go build with the -ldflags, probably somewhere on the main sysl repo. If you don't want to jump on that right now, could you create an issue for it?

2020-03-30 00:11 UTC, andrewemeryanz requested changes
This pull request now contains the changes from your other branch. I'll contact you on Slack to get this over the line.

2020-03-30 01:24 UTC, andrewemeryanz commented
> One more thing that would be super helpful for any users is to document ...
Issue created: https://github.com/anz-bank/sysl-go/issues/54

2020-03-30 02:44 UTC, andrewemeryanz commented
#major change.

2020-03-30 23:09 UTC, andrewemeryanz approved these changes

2020-03-30 23:09 UTC, merged